"use client";

import { useImperativeHandle, forwardRef } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { cn } from "@/lib/utils";
import {
    RiInformationLine,
    RiGlobalLine,
    RiSpeedLine,
    RiTerminalBoxLine,
} from "@remixicon/react";

import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    Form,
    FormControl,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form";

import { useBandwidthStore } from "../../store/bandwidth";
import { BandwidthFormData, bandwidthSchema, useCreateBandwidth } from "../../api/post-bandwidth";
import { useUpdateBandwidth } from "../../api/put-bandwidth";
import { useBandwidth } from "../../api/get-bandwidth";

type BandwidthFormProps = {
    mode: "new" | "edit" | "details";
    onSuccess?: () => void;
    bandwidthCode?: string;
    readOnly?: boolean;
};

export type BandwidthFormRef = {
    submit: () => void;
    isPending: boolean;
};

export const BandwidthForm = forwardRef<BandwidthFormRef, BandwidthFormProps>(
    ({ onSuccess, bandwidthCode, readOnly = false, mode }, ref) => {
        const { closeBandwidthFormSheet, selectedBandwidth } = useBandwidthStore();
        const isVerticalSidebar = process.env.NEXT_PUBLIC_SIDEBAR === "vertical";

        const { data: bandwidthData, isLoading: isLoadingBandwidth } = useBandwidth({
            code: bandwidthCode || "",
            queryConfig: { enabled: !!bandwidthCode },
        });

        const data = bandwidthData?.data || selectedBandwidth;
        
        const form = useForm<BandwidthFormData>({
            resolver: zodResolver(bandwidthSchema) as any,
            values: (data && mode !== "new") ? {
                name: data.name || "",
                code: data.code || "",
                data_owner: data.data_owner || "",
                download_mbps: String(data.download_mbps ?? 0),
                upload_mbps: String(data.upload_mbps ?? 0),
                min_rate_up: String(data.min_rate_up ?? 0),
                max_rate_up: String(data.max_rate_up ?? 0),
                min_rate_down: String(data.min_rate_down ?? 0),
                max_rate_down: String(data.max_rate_down ?? 0),
                min_rate_up_unit: data.min_rate_up_unit || "Mbps",
                max_rate_up_unit: data.max_rate_up_unit || "Mbps",
                min_rate_down_unit: data.min_rate_down_unit || "Mbps",
                max_rate_down_unit: data.max_rate_down_unit || "Mbps",
                rate_limit: data.rate_limit || "",
                attributes: {
                    service_profile: data.attributes?.service_profile || "residential",
                },
            } : {
                name: "",
                code: "",
                data_owner: "radius_admin",
                download_mbps: "0",
                upload_mbps: "0",
                min_rate_up: "0",
                max_rate_up: "0",
                min_rate_down: "0",
                max_rate_down: "0",
                min_rate_up_unit: "Mbps",
                max_rate_up_unit: "Mbps",
                min_rate_down_unit: "Mbps",
                max_rate_down_unit: "Mbps",
                rate_limit: "",
                attributes: {
                    service_profile: "residential",
                },
            }
        });

        const { mutate: createBandwidth, isPending: isCreating } = useCreateBandwidth({
            mutationConfig: {
                onSuccess: () => {
                    form.reset();
                    closeBandwidthFormSheet();
                    onSuccess?.();
                },
            },
        });

        const { mutate: updateBandwidth, isPending: isUpdating } = useUpdateBandwidth({
            mutationConfig: {
                onSuccess: () => {
                    form.reset();
                    closeBandwidthFormSheet();
                    onSuccess?.();
                },
            },
        });

        const isPending = isCreating || isUpdating;

        useImperativeHandle(ref, () => ({
            submit: () => {
                form.handleSubmit(onSubmit)();
            },
            isPending,
        }));

        const onSubmit = (formData: BandwidthFormData) => {
            // Convert strings back to numbers for the API
            // CRITICAL: We omit 'code' from the payload to avoid the "unknown field" 400 error,
            // as the code is provided in the URL or generated by the backend.
            const { code, ...restData } = formData;
            const payload = {
                ...restData,
                download_mbps: Number(formData.download_mbps),
                upload_mbps: Number(formData.upload_mbps),
                min_rate_up: Number(formData.min_rate_up),
                max_rate_up: Number(formData.max_rate_up),
                min_rate_down: Number(formData.min_rate_down),
                max_rate_down: Number(formData.max_rate_down),
            };

            if (mode === "edit" && bandwidthCode) {
                updateBandwidth({ code: bandwidthCode, data: payload as any });
            } else {
                createBandwidth(payload as any);
            }
        };

        if (isLoadingBandwidth) {
            return (
                <Card className="mt-[10px] mx-6">
                    <CardContent className="py-6">
                        <div className="text-center text-muted-foreground animate-pulse">
                            Loading bandwidth data...
                        </div>
                    </CardContent>
                </Card>
            );
        }

        return (
            <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col h-full overflow-hidden">
                    <Card className="flex-1 border-none shadow-none bg-transparent">
                        <CardContent className="p-0 flex flex-col h-full overflow-hidden">
                            <div className={cn("flex h-full grow flex-wrap px-3.5", { "lg:flex-nowrap": !isVerticalSidebar })}>
                                <div className={cn("grow py-5", { "border-border lg:border-s": !isVerticalSidebar })}>
                                    <ScrollArea className="h-full">
                                        <div className="p-6 space-y-8 pb-6">
                                            {/* General Information */}
                                            <div className="space-y-4">
                                                <div className="flex items-center gap-2 pb-2 border-b border-border/50">
                                                    <RiInformationLine className="size-4 text-blue-500" />
                                                    <h3 className="text-sm font-semibold">General Information</h3>
                                                </div>

                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                                    <FormField
                                                        control={form.control}
                                                        name="name"
                                                        render={({ field }) => (
                                                            <FormItem>
                                                                <FormLabel>Plan Name</FormLabel>
                                                                <FormControl>
                                                                    <Input placeholder="e.g. Bandwidth 10M" {...field} disabled={readOnly || isPending} />
                                                                </FormControl>
                                                                <FormMessage />
                                                            </FormItem>
                                                        )}
                                                    />
                                                    <FormField
                                                        control={form.control}
                                                        name="code"
                                                        render={({ field }) => (
                                                            <FormItem>
                                                                <FormLabel>Plan Code</FormLabel>
                                                                <FormControl>
                                                                    <Input placeholder="e.g. BW-10M" {...field} disabled={readOnly || isPending} />
                                                                </FormControl>
                                                                <FormMessage />
                                                            </FormItem>
                                                        )}
                                                    />
                                                </div>

                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                                    <FormField
                                                        control={form.control}
                                                        name="data_owner"
                                                        render={({ field }) => (
                                                            <FormItem>
                                                                <FormLabel>Data Owner</FormLabel>
                                                                <FormControl>
                                                                    <Input placeholder="radius_admin" {...field} disabled={readOnly || isPending || mode === "details"} />
                                                                </FormControl>
                                                                <FormMessage />
                                                            </FormItem>
                                                        )}
                                                    />
                                                    <FormField
                                                        control={form.control}
                                                        name="attributes.service_profile"
                                                        render={({ field }) => (
                                                            <FormItem>
                                                                <FormLabel>Service Profile</FormLabel>
                                                                <Select disabled={readOnly || isPending} onValueChange={field.onChange} value={field.value}>
                                                                    <FormControl>
                                                                        <SelectTrigger>
                                                                            <SelectValue placeholder="Select Profile" />
                                                                        </SelectTrigger>
                                                                    </FormControl>
                                                                    <SelectContent>
                                                                        <SelectItem value="residential">Residential</SelectItem>
                                                                        <SelectItem value="business">Business</SelectItem>
                                                                        <SelectItem value="enterprise">Enterprise</SelectItem>
                                                                    </SelectContent>
                                                                </Select>
                                                                <FormMessage />
                                                            </FormItem>
                                                        )}
                                                    />
                                                </div>
                                            </div>

                                            {/* Speed Configuration */}
                                            <div className="space-y-4 pt-2">
                                                <div className="flex items-center gap-2 pb-1 border-b border-border/50">
                                                    <RiSpeedLine className="size-4 text-purple-500" />
                                                    <h3 className="text-sm font-semibold">Granular Rate Configuration</h3>
                                                </div>
                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
                                                    {/* Upload Rates */}
                                                    <div className="space-y-4">
                                                        <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Upload Speed</h4>
                                                        <div className="grid grid-cols-2 gap-4">
                                                            <FormField
                                                                control={form.control}
                                                                name="min_rate_up"
                                                                render={({ field }) => (
                                                                    <FormItem>
                                                                        <FormLabel>Min Rate Up</FormLabel>
                                                                        <FormControl>
                                                                            <Input type="number" {...field} disabled={readOnly || isPending} />
                                                                        </FormControl>
                                                                        <FormMessage />
                                                                    </FormItem>
                                                                )}
                                                            />
                                                            <FormField
                                                                control={form.control}
                                                                name="max_rate_up"
                                                                render={({ field }) => (
                                                                    <FormItem>
                                                                        <FormLabel>Max Rate Up</FormLabel>
                                                                        <FormControl>
                                                                            <Input type="number" {...field} disabled={readOnly || isPending} />
                                                                        </FormControl>
                                                                        <FormMessage />
                                                                    </FormItem>
                                                                )}
                                                            />
                                                        </div>
                                                    </div>

                                                    {/* Download Rates */}
                                                    <div className="space-y-4">
                                                        <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Download Speed</h4>
                                                        <div className="grid grid-cols-2 gap-4">
                                                            <FormField
                                                                control={form.control}
                                                                name="min_rate_down"
                                                                render={({ field }) => (
                                                                    <FormItem>
                                                                        <FormLabel>Min Rate Down</FormLabel>
                                                                        <FormControl>
                                                                            <Input type="number" {...field} disabled={readOnly || isPending} />
                                                                        </FormControl>
                                                                        <FormMessage />
                                                                    </FormItem>
                                                                )}
                                                            />
                                                            <FormField
                                                                control={form.control}
                                                                name="max_rate_down"
                                                                render={({ field }) => (
                                                                    <FormItem>
                                                                        <FormLabel>Max Rate Down</FormLabel>
                                                                        <FormControl>
                                                                            <Input type="number" {...field} disabled={readOnly || isPending} />
                                                                        </FormControl>
                                                                        <FormMessage />
                                                                    </FormItem>
                                                                )}
                                                            />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            {/* Summary Calculation */}
                                            <div className="space-y-4 pt-2">
                                                <div className="flex items-center gap-2 pb-1 border-b border-border/50">
                                                    <RiGlobalLine className="size-4 text-emerald-500" />
                                                    <h3 className="text-sm font-semibold">Mbps Display & Summary</h3>
                                                </div>
                                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                                    <FormField
                                                        control={form.control}
                                                        name="upload_mbps"
                                                        render={({ field }) => (
                                                            <FormItem>
                                                                <FormLabel>Upload (Mbps)</FormLabel>
                                                                <FormControl>
                                                                    <Input type="number" {...field} disabled={readOnly || isPending} />
                                                                </FormControl>
                                                                <FormMessage />
                                                            </FormItem>
                                                        )}
                                                    />
                                                    <FormField
                                                        control={form.control}
                                                        name="download_mbps"
                                                        render={({ field }) => (
                                                            <FormItem>
                                                                <FormLabel>Download (Mbps)</FormLabel>
                                                                <FormControl>
                                                                    <Input type="number" {...field} disabled={readOnly || isPending} />
                                                                </FormControl>
                                                                <FormMessage />
                                                            </FormItem>
                                                        )}
                                                    />
                                                </div>
                                                <FormField
                                                    control={form.control}
                                                    name="rate_limit"
                                                    render={({ field }) => (
                                                        <FormItem>
                                                            <FormLabel className="flex items-center gap-1.5"><RiTerminalBoxLine className="size-3" />Rate Limit String</FormLabel>
                                                            <FormControl>
                                                                <Input placeholder="e.g. 10M/10M" {...field} disabled={readOnly || isPending} />
                                                            </FormControl>
                                                            <FormMessage />
                                                        </FormItem>
                                                    )}
                                                />
                                            </div>
                                        </div>
                                    </ScrollArea>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </form>
            </Form>
        );
    }
);

BandwidthForm.displayName = "BandwidthForm";
